### ISSUE TITLE
Fabric

### ISSUE THREAD

**Issue by om3ga6400** [XxRexRaptorxX/ParticleSpawner#1]
will this be ported to fabric?

**Comment by om3ga6400** [comment]
also, dose this actively effect the smoker like in the example? like when installed dose it do that to the smokers

**Comment by om3ga6400** [comment]
and dose this actively effect any other blocks

**Comment by XxRexRaptorxX** [comment]
No fabric port is planned.

and the spawner does not actively influence other blocks, it is purely visual

**Comment by om3ga6400** [comment]
> No fabric port is planned.
> 
> and the spawner does not actively influence other blocks, it is purely visual

yeah that is what i meant. Dose the mod visually effect blocks when its just installed or is it just a util to spawn particles in, like via commands or something

**Comment by XxRexRaptorxX** [comment]
it's a block that you can place and then configure to spawn different particles in the desired strength and radius
